<script src="https://unpkg.com/mirador@latest/dist/mirador.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">

<div id="mirador-container" data-manifest-url="<?php echo $this->escapeHtml($manifestUrl); ?>"></div>

<script type="text/javascript">
    const miradorContainer = document.getElementById('mirador-container');
    const mirador = Mirador.viewer({
        id: 'mirador-container',
        windows: [
            {
                loadedManifest: miradorContainer.dataset.manifestUrl,
                thumbnailNavigationPosition: 'far-bottom'
            }
        ],
        osdConfig: {
            maxZoomPixelRatio: 100,
        },
    });
</script>
